### PR TITLE
Added WINNF.FT.S.SIQ.2

### PR DESCRIPTION
**Pull request by sushantparkhi**

### CODE REVIEW

**Comment by jcereced** [comment]
it looks good!  Just one question on the TC itself, it say " by recording a Grandfathered Wireless Protection Zone (GWPZ) in the upper part of the band "  The WISP we are injecting is 3620-3620.  Is upper band 3600-3700 or 3650-3700?

**Comment by kate-harrison** [comment]
I'm going to take the liberty of closing this pull request so that I can deprecate the "needs updates to match test case" label (this is the last PR with that label) which is causing a small amount of confusion. This PR is based on a very old version of the test spec (before the ID renumbering) and thus is not directly applicable to our current efforts.

**Comment by jni2000** [comment]
do we need to rework on this ?

**Comment by jni2000** [comment]
Kate,

Do we need to rework on this ? What is the next step plan ?

James Ni
Director of SAS System
www.federatedwireless.com<http://www.federatedwireless.com/>
https://www.linkedin.com/pub/james-ni/4/3b9/24a
978.996.7480
[Description: Macintosh HD:Users:Sam:Dropbox (Bluetext):Federated Wireless:Creative:Logo:Logo Lock Up:Final-Lockup:Federated Wireless No Tag:FedWireless-lockup-notag-web.png]

**Comment by kate-harrison** [comment]
This is an implementation of the old version of SIQ.2. RED has already committed the latest version of SIQ.2 so this PR is obsolete.

**Pull request closed without merging**
