### PR TITLE
Formally document our scheme for managing old and new IDs simultaneously.

### PR DESCRIPTION
**Pull request by kate-harrison**

### CODE REVIEW

**Comment by jcereced** [comment]
looks good

**Comment by kate-harrison** [comment]
Thanks! I listed you as the official reviewer for this change and will submit now (I assume you skipped GitHub's "mark approved" process unintentionally).

**Comment by jcereced** [comment]
yes...sorry...i'm horrible at following the proper process since i don't
know it...i'll use mark approved in the future

**Comment by kate-harrison** [comment]
No problem, it was meant to be a friendly comment--plus documentation in case anyone was worried that I had bypassed the usual process.

**Pull request merged**
