### PR TITLE
Dockerfile added for containerization

### PR DESCRIPTION
**Pull request by ericjohnlucas**
Dockerfile added for containerization. All of the dependancies required will be installed on an ubuntu container with the attached Dockerfile

### CODE REVIEW

**Comment by ericjohnlucas** [comment]
Hi @kate-harrison, my name is Eric. I don't have a particular affiliation. While dabbling with this code I just noticed that there were many dependencies required, some of which are platform dependent. The Dockerfile I committed saves a lot of time by just packaging all the code along with the dependancies into a Docker container so the code is immediately ready to run. In addition to this, the containerization allows the user to attach the Land Cover and Terrain data to the container as mounts...

I thought I would share this connivence with the community..

**Comment by kate-harrison** [comment]
Thanks for the help! Unfortunately in order to accept a contribution we need you to jump through a small legal hurdle. You'll need to contact Lee Pucker (CEO of the Wireless Innovation Forum) and let him know you'd like to contribute; he can guide you from there. Looking forward to working with you!

**Comment by kate-harrison** [comment]
Eric, were you able to get in contact with Lee and sign the agreement?

**Comment by ericjohnlucas** [comment]
Hi just emailed him. So I hope to hear back soon.

**Pull request closed without merging**
