### PR TITLE
fix the azimuthRadiationPattern setting error (issue #685)

### PR DESCRIPTION
**Pull request by jni2000**
Also please check if we need to do the same fix for 

src/harness/testcases/testdata/esc_sensor_record_0.json

### CODE REVIEW

**Comment by jni2000** [comment]
Please review the fix for esc_record_0.json. Also, "src/harness/testcases/testdata/esc_sensor_record_0.json" is not in line with the spec. Do we need to make change to it too ?

**Comment by jni2000** [comment]
This fix is for issue #685

**Comment by nasrinivasa** [comment]
"src/harness/testcases/testdata/esc_sensor_record_0.json" seems to have an omni pattern, the antenna gain is the same for all angles. Not sure if it was intentional.

**Comment by nasrinivasa** [comment]
I agree with you on that Kate.

**Pull request merged**
