### PR TITLE
NEW SDS testcases using new ID: SDS.1 to SDS.5

### PR DESCRIPTION
**Pull request by gilschieber**
SDS tests 1 to 5

### CODE REVIEW

**Comment by kate-harrison** [comment]
James, can you please help to review this PR? Thanks!

**Comment by jni2000** [comment]
Yes, I have assigned this fro reviewing, Will get back to you asap.

**Comment by jni2000** [comment]
We reviewed the test cases and here are our comments:

1. There are some overlapping with our submission "Fw sds6to19 #387". We do not think that is a big deal. If this submission can be checked in sooner than ours, we will pick them up.
2. Execution of the testcase threw the error “'sslv3 alert unsupported certificate')”. I think field “extendedKeyUsage = serverAuth” in [ oper_req ] and [ oper_req_sign ] sections of ‘cert/openssl.cnf’ has to be changed to “extendedKeyUsage = clientAuth”
3. The field FRN is an applicable field for the  ROLE:OPERATOR. It can be added into the ‘cert/openssl.cnf’ file.

Please take a look of our comments and let's move forward.

**Comment by gilschieber** [comment]
Please find your comments addressed below:

1. Overlapping issues with your #387 to be picked up by your submission later.
2. extendedKeyUsage changed from 'serverAuth' to 'clientAuth', thanks for pointing this out.
3. Added the FRN field into the ‘cert/openssl.cnf’ file. Also made some other cleaning/changes to this file (adding FCCID and SERIAL fields, removing deprecated fields (CBSDID, CATEGORY, STARTDATETIME).

Let me know if it's ok.

**Comment by jni2000** [comment]
All our comments have been addressed for this PR. We have verified them. Approved from us for merging into master.

**Comment by gilschieber** [comment]
Merged #379

**Comment by jni2000** [comment]
great, I think we have only one issue to address in test cases SCS.6 - 20. I am asking our engineers to address it and any others if there are more. Please can you also help speedup the review and let the security test cases through and ready for use? Thanks.

**Comment by kate-harrison** [comment]
I have replied to your comment in #371 directly.

**Pull request merged**
