### PR TITLE
Fw sds6to19

### PR DESCRIPTION
**Pull request by jni2000**
Federated Wireless submitted the revised test cases SDS.6 -- SDS.19. Please review.

### CODE REVIEW

**Comment by jni2000** [comment]
This is the original review comments from Kate on the old obsolete pull request which has been closed and replaced by this one.  (https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/pull/373)

 src/harness/sas_interface.py
@@ -230,6 +230,17 @@ def BlacklistByFccId(self, request):
     """
     pass
 
+  @abc.abstractmethod
+  def BlacklistDPByFRN(self, request):
@kate-harrison
kate-harrison 8 days ago Member

I don't think this is how cert blacklisting will work in normal operation. If it is, can you please provide some information that I can relay to the rest of test dev to explain this addition to the testing API?

My understanding is that we will use OCSP in normal operation and that the certs need to be blacklisted in that way.

**Comment by jni2000** [comment]
We have responded to all the review comments, can we move forward to approve them?

**Comment by kate-harrison** [comment]
This PR is based heavily off of PR #371 so we will wait to review until that PR is submitted, as agreed in #373.

**Comment by jni2000** [comment]
We are closing this PR and resubmit a new PR for SDS.6, 7,8,9,10,12,13,14,15 in a new PR that consolidated all the changes in the corresponding approved SCS test cases.

**Pull request closed without merging**
