### PR TITLE
Add relevant FDB data files

### PR DESCRIPTION
**Pull request by harinineelu**

### CODE REVIEW

**Comment by harinineelu** [comment]
Thanks Janet, Fixed the merge issues. Could you please take a look.

**Comment by jni2000** [comment]
Just one comment: I remembered that Kate asked not to delete FDB.7 test case from the test file. I noticed that it was deleted. Please confirm with Kate on this.

**Comment by harinineelu** [comment]
Sorry about the confusion. The addition and deletion of the same files caused some ugly merge conflicts. PR #600 is the same as this one. Could you pls take a look at that. I'm abandoning this one. Thanks!

**Comment by kate-harrison** [comment]
James: I asked Harini to delete that code but keep it locally. We are still working out the fate of FDB.7 so it will not be included for now.

**Comment by kate-harrison** [comment]
Changes were made in PR #600 so we can close this one.

**Pull request closed without merging**
