### PR TITLE
Prop Models: Implement minimum height of 1m

### PR DESCRIPTION
**Pull request by sbdt-google**
As proposed in WG1 specification change (note: not yet integrated in spec), to use minimum of 1m height.
Also add following changes:
 - remove the exception check for maximum height
 - add a flag parameter to specify if CBSD height is a AMSL height. Using this flag will simplify the test harness code logic, as it wont need to do the test for AMSL and correction in various places. 

Background:
The models are not designed for negative height, and would return bogus results.
Normally AGL height should always be positive (except for CBSD in basement or tunnels or subway), although an error in configuration would go through the SAS-CBSD protocol. 
Problematic also is the height being specified as AMSL. This AMSL would be transformed into an AGL height by removing the terrain height coming from the terrain database, which may be inaccurate, and thus leading to a negative height for purpose of propagation modeling.

To avoid having the bogus result preventing a CBSD interference to be taken into account during incumbents protection, a minimum height of 1m is taken into account.
Most likely, valid underground CBSD will be handled as part of a future extension of the SAS specification, with a specific modeling and specific flag for categorizing those

### CODE REVIEW

**Comment by jni2000** [comment]
I have reviewed the general logic and they looks Google. We are in process of another round of reviewing of the functions.

**Comment by sbdt-google** [comment]
Ok let me know, the change are pretty simple, and in agreement with the change in spec done recently.

**Comment by jni2000** [comment]
Serge, Mo has reviewed the functional portion and all looks good. Please merge in.

**Comment by sbdt-google** [comment]
Thanks. submitted

**Pull request merged**
