### PR TITLE
Whitelist fccIds by injecting before FAD

### PR DESCRIPTION
**Pull request by arhannan**
Change based on Issue 799
https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/issues/799#issuecomment-421357895

### CODE REVIEW

**Comment by arhannan** [comment]
We can make the change inside sas_test_harness.writeFadRecord. That however will require calling sas_admin from sas_test_harness. Either we have to setup the Admin API in sas_test_harness or pass it into sas_test_harness. Won’t it be easier to call sas_admin.InjectFccId whenever writeFadRecord is called? 
I.e make changes in these files WINNF_FT_S_FAD_testcase.py WINNF_FT_S_GRA_testcase.py WINNF_FT_S_IPR_testcase.py WINNF_FT_S_MCP_testcase.py

**Comment by kate-harrison** [comment]
You have a good point that the Admin API is not currently accessible to the SAS Test Harness. I think it should be relatively simple to add it, but I agree that it could also be quite confusing since the SAS TH is not logically connected to the SAS UUT Admin API.

My concern is that the code proposed here will have to be repeated in a number of places (e.g. there are 7 IPR tests, each with the potential for SAS THs) and that leaves a lot of opportunity for error -- especially because the current implementation is a little more complicated than necessary. I would feel more comfortable with your proposal if we could at least encapsulate the code here into a function (living in sas_testcase.py) which can be called from each of the necessary locations:

```
def InjectTestHarnessFccIds(self, cbsd_records):
  logging.info('Injecting FCC IDs for CBSDs in the SAS test harness into the SAS UUT.')
  for cbsd_record in cbsd_records:
    self._sas_admin.InjectFccId({'fccId': cbsd_record['registration']['fccId']})
```

then e.g. the code in MCP looks like:

```
...
self.InjectTestHarnessFccIds(test_harness_data['cbsdRecords'])
test_harness.writeFadRecords([test_harness_data['cbsdRecords']]) # no change here
...
```
and it would be a similarly small change to the other test cases. What do you think about this?

**Comment by arhannan** [comment]
I agree with you. Your proposal is a good idea. We'll make the changes

**Comment by kate-harrison** [comment]
Sounds great, thank you! I'll be OOO soon, so Taran from Google will make sure that your PR is reviewed quickly if I'm unable to do so myself.

**Comment by arhannan** [comment]
Thanks @kate-harrison . We have checked in the new changes. We modified MCP, GRA and FAD.

**Pull request merged**
