### PR TITLE
Fw pcr.7fix

### PR DESCRIPTION
**Pull request by jni2000**
In PCR7 a zone is injected into the SUUT

/admin/injectdata/zone :

{"record": {"terminated": false, "name": "PPA Zone 0", "zone": {"type": "Polygon", "coordinates": [[[-100.61355286470628, 39.06028870255636], [-100.6103309414228, 39.05904150644663], [-100.60427196105131, 39.056756972863944], [-100.60425345765879, 39.05674997526318], [

This is not consistent with the zones we inject in other TCs:

/admin/injectdata/zone :

{"record": {"terminated": false, "name": "PPA Zone 0", "zone": {"type": "FeatureCollection", "features": [{"geometry": {"type": "Polygon", "coordinates": [[[-97.23861694335938, 38.865374851611634], [-97.31964111328125, 38.7615795117574], [-97.16995239257811, 38.739088441876866], [-97.16171264648436, 38.86751337001198], [-97.2386

It looks like the zone record in the PCR 7 config was not created properly

The second one is the correct one and what the PCR7 config should look like when it’s fixed

### CODE REVIEW

**Comment by jni2000** [comment]
Kate and Javi

Please help review the fix of PCR.7 issues Javi reported.

Thanks.

**Comment by jcereced** [comment]
Looks like we got the front of it done but there is an issue on the back part of the JSON  now:

 

 

It’s still missing:

 

"type": "Feature",
        "properties": {},
 

 

Once I added that to default.config it injects properly onto the SUUT

 

 

 

Please refer to :

 

https://raw.githubusercontent.com/Wireless-Innovation-Forum/Spectrum-Access-System/master/src/harness/testcases/testdata/ppa_record_0.json

 

 

 

 

{

  "name": "PPA Zone 0",

  "creator": "admin_0",

  "usage": "PPA",

  "terminated": false,

  "ppaInfo": {

    "cbsdReferenceId": [],

    "ppaRegionType": "URBAN"

  },

  "zone": {

    "type": "FeatureCollection",

    "features": [

      {

        "type": "Feature",

        "properties": {},

        "geometry": {

          "type": "Polygon",

          "coordinates": [

            [

              [

                -97.23861694335938,

                38.865374851611634

              ],

              [

                -97.31964111328125,

                38.7615795117574

              ],

              [

                -97.16995239257811,

                38.739088441876866

              ],

              [

                -97.16171264648436,

                38.86751337001198

              ],

              [

                -97.23861694335938,

                38.865374851611634

              ]

            ]

          ]

        }

      }

    ]

  }

}

**Comment by jni2000** [comment]
Thanks, Javi. Fixed now. Please review.

**Comment by jni2000** [comment]
Thanks.

**Pull request merged**
