### PR TITLE
NEW SCS testcases: SCS_1 to 5

### PR DESCRIPTION
**Pull request by norbertbarbosa**
Implementation of the new SCS.1, 2, 3, 4, and 5 testcases.
The SDS and SSS 1 to 5 will be also derived from these tests

### CODE REVIEW

**Comment by jni2000** [comment]
Federated Wireless has finished reviewing the "NEW SCS testcases: SCS_1 to 5" done by google. Looks good as of what we understand.

**Comment by kate-harrison** [comment]
Thank you! Just to make sure there's no miscommunication, can we considered
the pull request officially approved by Federated Wireless?

FYI we typically conduct the reviews via the GitHub interface. Sony has a
special exception due to the restrictions imposed by their legal department
but it's best if everyone who can use the GitHub interface does -- it makes
it easier to track accountability.

Thanks!

Kate

Am Mittwoch, 20. Dezember 2017 schrieb James Ni :

**Comment by jni2000** [comment]
Yes, we used Github interfeces.

James Ni
Director of SAS System
www.federatedwireless.com<http://www.federatedwireless.com/>
https://www.linkedin.com/pub/james-ni/4/3b9/24a
978.996.7480
[Description: Macintosh HD:Users:Sam:Dropbox (Bluetext):Federated Wireless:Creative:Logo:Logo Lock Up:Final-Lockup:Federated Wireless No Tag:FedWireless-lockup-notag-web.png]

**Comment by kate-harrison** [comment]
Yes, sorry, I misread the automatic email and thought you had sent it
yourself.

**Pull request merged**
